/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo_final;

import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class TrabajoFinal extends javax.swing.JFrame {

    int x = 40;
    int y = 40;
    int n = 0;
    BinarySearchTree arbol = new BinarySearchTree();
    JOptionPane t;

    /**
     * Creates new form TrabajoFinal
     */
    public TrabajoFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnCrearNodo = new javax.swing.JButton();
        txtDat = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lbAdvertencias = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 500));
        setResizable(false);

        btnCrearNodo.setBackground(new java.awt.Color(255, 255, 0));
        btnCrearNodo.setText("Ingresar Nodos");
        btnCrearNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNodoActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 204));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setText("Eliminar Nodos");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbAdvertencias.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdvertencias, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearNodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addGap(33, 33, 33)
                .addComponent(btnEliminar)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearNodo)
                    .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar)
                    .addComponent(lbAdvertencias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNodoActionPerformed
        // TODO add your handling code here:
        leerTxt(1);
    }//GEN-LAST:event_btnCrearNodoActionPerformed

    public void leerTxt(int action) {
        String tex = txtDat.getText().toString();
        String[] aux3 = tex.split(",");
        int contAux = 0;
        int contAux2 = 0;
        int contAux3 = 0;

        if (aux3.length > 0) {
            for (int i = 0; i <= aux3.length - 1; i++) {
                String elementoXPocion = aux3[i];
                if (elementoXPocion.equals("")) {
                    System.out.println("Despues de cada coma debe ir un número");
                    lbAdvertencias.setText("Despues de cada coma debe ir un número");
                    JOptionPane.showMessageDialog(this, "Despues de cada coma debe ir un número", "Error!", JOptionPane.OK_CANCEL_OPTION);
                    contAux3++;
                } else {

                    for (int e = 0; e < elementoXPocion.length(); e++) {
                        if (!Character.isDigit(aux3[i].charAt(e))) {
                            contAux++;
                        } else {
                            contAux2++;
                        }
                    }
                }
            }

            if (contAux == 0 && contAux3 == 0) {
                String[] numeros;
                if (txtDat.getText().contains(",")) {
                    numeros = txtDat.getText().split(",");
                } else {
                    numeros = txtDat.getText().split("");
                }
                if (numeros.length > 9) {
                    System.out.print("El límite de números es 9");
                    lbAdvertencias.setText("El límite de números es 9");
                    JOptionPane.showMessageDialog(this, "El límite de números es 9", "Error!", JOptionPane.OK_CANCEL_OPTION);
                } else {
                    if (action == 1) {
                        CrearArbol(numeros);
                        Mostrar();
                    } else if (action == 2) {
                        eliminar(numeros);
                        Graphics p = this.getGraphics();
                        super.paintComponents(p);
                        Mostrar();
                    }
                }
            } else {
                System.out.print("Debe colocar numeros separados por coma");
                lbAdvertencias.setText("Debe colocar numeros separados por coma");
                JOptionPane.showMessageDialog(this, "Debe colocar numeros separados por coma", "Error!", JOptionPane.OK_CANCEL_OPTION);
            }
        }
    }


    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        arbol.AllDelete();
        Graphics p = this.getGraphics();
        super.paintComponents(p);
        lbAdvertencias.setText(null);
        txtDat.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        leerTxt(2);
        txtDat.setText(null);
        lbAdvertencias.setText(null);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void CrearArbol(String[] numeros) {
        for (int i = 0; i < numeros.length; i++) {
            arbol.Add(Integer.parseInt(numeros[i]), lbAdvertencias, t, this);
        }
        arbol.LevelOrder();
    }

    private void Mostrar() {
        Graphics p = this.getGraphics();
        arbol.graficar(p);
    }

    private void eliminar(String[] numeros) {
        for (int i = 0; i < numeros.length; i++) {
            arbol.Delete(Integer.parseInt(numeros[i]));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabajoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabajoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabajoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabajoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrabajoFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearNodo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbAdvertencias;
    private javax.swing.JTextField txtDat;
    // End of variables declaration//GEN-END:variables

}
